### ISSUE TITLE
Include tests in source tarball

### ISSUE THREAD

**Issue by jayvdb** [jimo1001/docutils-ast-writer#2]
When they are missing, `setup.py test` fails

```
[   71s] + /usr/bin/python3 setup.py test
[   72s] running test
[   72s] running build_py
[   72s] running egg_info
[   72s] creating /home/abuild/rpmbuild/BUILD/docutils-ast-writer-0.1.2/build/lib/docutils_ast_writer.egg-info
[   72s] writing /home/abuild/rpmbuild/BUILD/docutils-ast-writer-0.1.2/build/lib/docutils_ast_writer.egg-info/PKG-INFO
[   72s] writing dependency_links to /home/abuild/rpmbuild/BUILD/docutils-ast-writer-0.1.2/build/lib/docutils_ast_writer.egg-info/dependency_links.txt
[   72s] writing entry points to /home/abuild/rpmbuild/BUILD/docutils-ast-writer-0.1.2/build/lib/docutils_ast_writer.egg-info/entry_points.txt
[   72s] writing requirements to /home/abuild/rpmbuild/BUILD/docutils-ast-writer-0.1.2/build/lib/docutils_ast_writer.egg-info/requires.txt
[   72s] writing top-level names to /home/abuild/rpmbuild/BUILD/docutils-ast-writer-0.1.2/build/lib/docutils_ast_writer.egg-info/top_level.txt
[   72s] writing manifest file '/home/abuild/rpmbuild/BUILD/docutils-ast-writer-0.1.2/build/lib/docutils_ast_writer.egg-info/SOURCES.txt'
[   72s] reading manifest file '/home/abuild/rpmbuild/BUILD/docutils-ast-writer-0.1.2/build/lib/docutils_ast_writer.egg-info/SOURCES.txt'
[   72s] writing manifest file '/home/abuild/rpmbuild/BUILD/docutils-ast-writer-0.1.2/build/lib/docutils_ast_writer.egg-info/SOURCES.txt'
[   72s] running build_ext
[   72s] Traceback (most recent call last):
[   72s]   File "setup.py", line 22, in <module>
[   72s]     use_2to3 = True
[   72s]   File "/usr/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
[   72s]     return distutils.core.setup(**attrs)
[   72s]   File "/usr/lib64/python3.7/distutils/core.py", line 148, in setup
[   72s]     dist.run_commands()
[   72s]   File "/usr/lib64/python3.7/distutils/dist.py", line 966, in run_commands
[   72s]     self.run_command(cmd)
[   72s]   File "/usr/lib64/python3.7/distutils/dist.py", line 985, in run_command
[   72s]     cmd_obj.run()
[   72s]   File "/usr/lib/python3.7/site-packages/setuptools/command/test.py", line 228, in run
[   72s]     self.run_tests()
[   72s]   File "/usr/lib/python3.7/site-packages/setuptools/command/test.py", line 235, in run_tests
[   72s]     module = self.test_suite.split('.')[0]
[   72s] AttributeError: 'NoneType' object has no attribute 'split'
[   72s] error: Bad exit status from /var/tmp/rpm-tmp.GXkxJU (%check)
```

**Comment by jayvdb** [comment]
There are also no tags at https://github.com/jimo1001/docutils-ast-writer/releases 

So at https://build.opensuse.org/package/show/home:jayvdb:coala:python3-bears/python-docutils-ast-writer , how do I get the tests which correspond to 0.1.2 ?

I can guess that https://github.com/jimo1001/docutils-ast-writer/tree/f930ad7fc30288e9719d4d74b8c9caee647360cb corresponds to the 0.1.2 release.
